LSETAPE = [
    # Spec: https://www.data.boem.gov/Main/HtmlPage.aspx?page=leaseData
    ("lease_number", 7),
    ("filler.1", 8),
    ("serial_type", 1),
    ("sale", 7),
    ("filler.2", 4),
    ("exp", 8),  # TODO INVESTIGATE
    ("county_code", 5),
    ("tract", 10),
    ("eff", 8),  # TODO INVESTIGATE
    ("term", 2),
    ("exp2", 8),  # TODO INVESTIGATE
    ("bid_code", 5),
    ("royalty_rate", 10),
    ("filler.3", 3),
    ("initial_area", 14),
    ("current_area", 14),
    ("rent_per_unit", 8),
    ("bid_amount", 13),
    ("bid_per_unit", 13),
    ("filler.4", 1),
    ("low_water_depth", 5),
    ("max_water_depty", 5),
    ("measure_flag", 1),
    ("mms_planning_code", 3),
    ("filler.5", 2),
    ("district_code", 2),
    ("filler.6", 3),
    ("lease_status_code", 6),
    ("lease_status_effective", 8),
    ("suspension_expiration", 8),
    ("suspension_type", 1),
    ("well_name", 6),
    ("well_type", 1),
    ("lease_qualifying", 8),
    ("discovery_type", 3),
    ("field_discover_code", 1),
    ("distance_to_shore", 3),
    ("filler.7", 1),
    ("num_platforms", 3),
    ("platform_approval", 8),
    ("first_platform_set", 8),
    ("lease_section", 2),
    ("postal_state", 4),
    ("lease_area", 12),
    ("protraction", 7),
    ("filler.8", 8),
    ("suspension_effective", 8),
    ("first_production", 8),
    ("filler.9", 4),
    ("area_code", 2),
    ("filler.10", 2),
    ("block_number", 6),
    ("filler.11", 2),
]

LSEOWND = [
    # Spec: https://www.data.boem.gov/Main/HtmlPage.aspx?page=leaseOwnerOper
    ("lease_number", 7),
    ("assignment_approved", 8),
    ("assignment_effective", 8),
    ("assignment_status", 1),
    ("group", 1),
    ("company_num", 5),
    ("percentage", 11),
    ("designation", 8),
    ("operator_num", 5),
]

COMPALL = [
    # Spec: https://www.data.boem.gov/Main/HtmlPage.aspx?page=companyAll
    ("mms_number", 5),
    ("start", 8),
    ("name", 100),
    ("sort_name", 75),
    ("terminated", 8),
    ("region_pac", 1),
    ("region_gom", 1),
    ("region_alaska", 1),
    ("region_atl", 1),
    ("duns", 13),
    ("termination_effective", 8),
    ("termination_code", 1),
    ("division_name", 35),
    ("address_one", 35),
    ("address_two", 35),
    ("city", 35),
    ("state", 2),
    ("zip_code", 20),
    ("country", 35),
]
