name: Run Test Suite

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run ward

  pylint:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run pylint weblease


  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run mypy --strict weblease
